server:
  port: 1109

spring:
  datasource:
    username: root
    password: JunMo_123
    url: jdbc:mysql://192.168.31.23:3306/dao-bi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations:
    - classpath:mybatis-mapper/*.xml

dao-bi:
  # 支持数据源类型, 启动时按需加载处理器
  data-source-type: mysql、excel